# Generated by Django 4.2 on 2023-08-29 20:33

import Twitter.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст поста')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Имаге')),
                ('likes', models.BigIntegerField(default=0, verbose_name='Количество классов')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, unique=True, verbose_name='Тег')),
                ('posts', models.ManyToManyField(blank=True, to='Twitter.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=150, verbose_name='Отображаемое имя пользователя')),
                ('avatar', models.ImageField(default='default/default_user_avatar.jpg', upload_to=Twitter.models.user_profile_avatar_path)),
                ('bio', models.TextField(blank=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='Twitter.profile')),
            ],
        ),
    ]
