# Generated by Django 4.2 on 2023-09-01 11:36

import Twitter.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customUser', '0001_initial'),
        ('Twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, unique=True, verbose_name='Тег')),
                ('posts', models.ManyToManyField(blank=True, to='Twitter.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(blank=True, default=None, max_length=150, verbose_name='Отображаемое имя пользователя')),
                ('avatar', models.ImageField(default='default/default_user_avatar.jpg', upload_to=Twitter.models.user_profile_avatar_path)),
                ('bio', models.TextField(blank=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='Twitter.profile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='Twitter.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='profile_liked', to='Twitter.profile', verbose_name='Классы'),
        ),
    ]
