# Generated by Django 4.2 on 2023-08-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Twitter.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
