# Generated by Django 4.2 on 2023-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0002_alter_post_post_images_alter_post_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_images',
        ),
        migrations.AddField(
            model_name='post',
            name='post_thumbs',
            field=models.CharField(blank=True, default='/', max_length=255),
        ),
    ]
