# Generated by Django 4.2 on 2023-08-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_remove_post_post_images_post_post_thumbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_Image', models.ImageField(upload_to='')),
                ('test_field_File', models.FileField(upload_to='')),
            ],
        ),
    ]
