# Generated by Django 4.2 on 2023-08-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
