# Generated by Django 4.2 on 2023-08-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0005_post_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_thumbs',
        ),
    ]
