# Generated by Django 5.0.1 on 2024-01-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default=None, null=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='image',
            name='post_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.post'),
        ),
    ]
