# Generated by Django 4.2 on 2023-09-01 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст поста')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Имаге')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
